### ISSUE TITLE
Email message is not visible...but it is attached!

### ISSUE THREAD

**Issue by shinesoftware** [magepal/magento2-gmail-smtp-app#165] opened 2020-03-23 10:53 UTC
#### Magento version #: 
2.3.4

#### Edition (EE, CE, OS, etc): 
CE

#### Expected behavior: 
Read the email message content

#### Actual behavior: 
After the last update the text message content is hidden and a file (attachment.html) is attached to the email as shown in the image.

#### Steps to reproduce: 
Run the test and check the **Hello from MagePal SMTP (2 of 2)**

![Selezione_023](https://user-images.githubusercontent.com/1553035/77309372-d3408200-6cfc-11ea-999f-c65ca422323f.png)

**Comment by srenon** [comment] 2020-03-23 12:30
I'm not able to reproduce this issue using Magento 2.3.4 (with Gmail), so this would require further debugging

![image](https://user-images.githubusercontent.com/1415141/77316720-4d164280-6ce0-11ea-9adf-b2bdcd8088ba.png)

**Comment by shinesoftware** [comment] 2020-03-23 15:05
Yes it is really weird! I have a different behaviour in local enviroment and in the production enviroment. Do you have a clue?

**Comment by shinesoftware** [comment] 2020-03-24 16:51
I am debugging the code and I have discovered this weird behavior using your module. Check the image.
![Selezione_024](https://user-images.githubusercontent.com/1553035/77453848-15022300-6df8-11ea-83bd-4d07d0e6c395.png)

**Comment by shinesoftware** [comment] 2020-03-25 08:21
After a little debug I have noticed that the composer version generates the issue that I have posted here. After the installation by a simple copy of the module in the "app" directory I can receive the message email correctly. The version installed is the 1.5.1. Any clue?

![Selezione_025](https://user-images.githubusercontent.com/1553035/77515848-951c9d00-6e79-11ea-8a88-169d00d40094.png)

**Comment by jamie-selesti** [comment] 2020-03-26 08:09
I am not sure if the issue I have just raised is related https://github.com/magepal/magento2-gmail-smtp-app/issues/166

**Comment by shinesoftware** [comment] 2020-03-26 10:17
> I am not sure if the issue I have just raised is related #166

No because we have not that error:

    PHP Fatal error: Uncaught Error: Call to a member function setEncoding() on bool in /var/www/vhosts/domain.com/vendor/magepal/magento2-gmailsmtpapp/Model/TwoDotThree/Smtp.php

mentioned at https://github.com/magepal/magento2-gmail-smtp-app/issues/166

**Comment by srenon** [comment] 2020-03-27 14:19
This issue should be fixed in 2.8.0 which will be released shortly

**Comment by srenon** [comment] 2020-03-27 17:36
@shinesoftware ... what email client (webmail, Mac Mail, Thunderbird, Outlook etc) are you using?

Please download 2.8.0 and let me know if you are still having issues

**Closed by srenon** 2020-03-27 17:36 UTC

**Comment by shinesoftware** [comment] 2020-03-28 19:56
I am using the zoho.eu mail server. I'll check your latest version asap!

**Comment by shinesoftware** [comment] 2020-04-01 07:22
> Please download 2.8.0 and let me know if you are still having issues

@srenon the dev-master alias 2.8.0 works! Thanks guys!
